---
store:
  on_change: false            # save if state changed. # default false
  retention: 24h              # retention period for data. # default 24h

collectors:
  - interval: 5s              # you can initiate more collectors with different intervals.
    type: systemd             # type can be: systemd
    nodes:
      - ip: client-ip-addr
        username: client-username
        services:
          - name: redis
            group: redis
            importance: low
            ports:
              - 7001
          - name: nginx
            group: frontend
            importance: low

      - ip: another-client-ip-addr
        username: client-username
        services:
          - name: frontend
            group: frontend
            importance: high

  - interval: 2s
    type: systemd
    nodes:
      - ip: client-ip-addr
        username: client-username
        services:
          - name: coredns
            group: dns
            importance: low

      - ip: yet-another-client-ip-addr
        username: client-username
        services:
          - name: coredns
            group: dns
            importance: low

database:
  path: /path/to/store/sqlite.db

http:
  host: 0.0.0.0
  port: 8080
...